export const COLORS = {
  defaultLight: "#D8B0F7",
  defaultBold: "#9A71F0",
  defaultWarning: "#ff5447",
  defaultWhite: "#fff",
  defaultOrange: "#ff5100",
  defaultOrangeLight: "#f7a16f",
  defaultLemon: "#f6ff7c",
  defaultBlueLight: "#AECDFF",
  defaultBlueBold: "#0A82FF",
  defaultGray: "#888",
  defaultGrayLight: "#d2d2d2",
  defaultPinkLight: "#FEC6C8",
  defaultPinkBold: "#ff71a1",
};
